#!/bin/bash
# Iteratively link the M3 kernel, harvesting undefined symbols into
# auto-generated tracing stubs (port/stubs/autostubs.c) until the link
# closes.  Hand-implemented symbols live in sgi_glue.c / the ml layer
# and are never auto-stubbed.  Symbols listed in datasyms.txt become
# zeroed arrays instead of functions.
cd "$(dirname "$0")/.."

OBJS="$*"
AUTOC=stubs/autostubs.c
DATA=stubs/datasyms.txt
touch "$DATA"

cat > "$AUTOC" <<'EOF'
/*
 * AUTO-GENERATED by port/scripts/genstubs.sh — do not edit by hand.
 * Tracing stubs for symbols original SGI code references but the port
 * has not implemented yet.  Each prints once on first call, then
 * returns 0, so main() runs as deep as possible while reporting
 * exactly which subsystems it touches.
 */
extern void kprintf(const char *fmt, ...);
#define STUB(name) \
	long name(void) { \
		static int hit; \
		if (!hit++) kprintf("  [stub] " #name "\n"); \
		return 0; \
	}
EOF

# compile the freshly-truncated stub file so the first link test never
# sees a stale autostubs.o from a previous run
mkdir -p obj
scripts/tryc.sh "$PWD/$AUTOC" -o "$PWD/obj/autostubs.o" || exit 1

for pass in $(seq 1 40); do
	UND=$(ld.lld -nostdlib -static -z max-page-size=0x1000 \
		-T build/linker.ld $OBJS obj/autostubs.o -o /dev/null 2>&1 |
		sed -n 's/.*undefined symbol: \([A-Za-z_][A-Za-z0-9_]*\).*/\1/p' |
		sort -u)
	[ -z "$UND" ] && { echo "LINK CLOSED after $((pass-1)) passes"; exit 0; }
	n=0
	for s in $UND; do
		grep -q "\b$s\b" "$AUTOC" && continue
		if grep -qx "$s" "$DATA"; then
			echo "unsigned long $s[512];" >> "$AUTOC"
		else
			echo "STUB($s)" >> "$AUTOC"
		fi
		n=$((n+1))
	done
	echo "pass $pass: +$n symbols"
	[ "$n" = "0" ] && { echo "no progress — dumping link error:"; \
		ld.lld -nostdlib -static -z max-page-size=0x1000 \
		-T build/linker.ld $OBJS obj/autostubs.o -o /dev/null 2>&1 | head -20; exit 1; }
	scripts/tryc.sh "$PWD/$AUTOC" -o "$PWD/obj/autostubs.o" || exit 1
done
