#!/bin/sh
# Build the M8 userland (crt0 + ulibc + init.c) into a compact ELF64 and
# regenerate the memfs file headers (init program + motd data file).
# Run from anywhere; writes port/fs/{init_elf.h,motd.h}.
set -e
cd "$(dirname "$0")"
UDIR=$(pwd)
FS=$UDIR/../fs

CC="clang --target=x86_64-elf -nostdlib -ffreestanding -fno-stack-protector \
    -fno-pic -mno-red-zone -mno-sse -O2 -c"

$CC crt0.S  -o /tmp/crt0.o
$CC ulibc.c -o /tmp/ulibc.o
$CC init.c  -o /tmp/uinit.o

# link at 0x400000, one compact PT_LOAD (reuse the ml linker script shape)
cat > /tmp/user.ld <<'EOF'
ENTRY(_start)
PHDRS { load PT_LOAD FLAGS(7); }
SECTIONS {
  . = 0x400000;
  .text : { *(.text*) } :load
  .rodata : { *(.rodata*) } :load
  .data : { *(.data*) } :load
  .bss : { *(.bss*) *(COMMON) } :load
  /DISCARD/ : { *(.comment) *(.note*) *(.eh_frame*) }
}
EOF
ld.lld -T /tmp/user.ld -z max-page-size=0x1000 -n \
    /tmp/crt0.o /tmp/ulibc.o /tmp/uinit.o -o /tmp/init.elf

emit_bytes() {	# $1=infile $2=cvar $3=outheader $4=guard
	{
	  echo "/* GENERATED by port/user/build-user.sh — do not edit. */"
	  echo "#ifndef $4"
	  echo "#define $4"
	  echo "static const unsigned char $2[] = {"
	  od -An -v -tu1 "$1" | awk '{for(i=1;i<=NF;i++)printf "%s%s",(c++%14==0?"\n\t":""),$i","}'
	  echo ""
	  echo "};"
	  echo "#endif"
	} > "$3"
}

emit_bytes /tmp/init.elf init_elf "$FS/init_elf.h" __MEMFS_INIT_ELF_H

printf 'Welcome to IRIX 6.5.7m on x86-64.\nThis file lives in memfs and was read through the VFS.\n' \
    > /tmp/motd.txt
emit_bytes /tmp/motd.txt motd_txt "$FS/motd.h" __MEMFS_MOTD_H

echo "init.elf: $(wc -c < /tmp/init.elf) bytes, entry $(llvm-readelf -h /tmp/init.elf | awk '/Entry/{print $NF}')"
echo "motd: $(wc -c < /tmp/motd.txt) bytes"
